// =====================================================================
// dom.js — App.svelte が描画したマークアップへの参照を一括取得する
//
// id を変更・追加した場合はここに追記する。各ビューは elements 経由でのみ
// DOM に触れる（直接 querySelector しない）ことで、参照箇所を追いやすくする。
// 例外: 走査エンジン（scan.js）と操作訓練のカーソル更新は動的要素を扱うため
// document.querySelector を併用している。
// =====================================================================

export function collectElements() {
  return {
    scanState: document.querySelector("#scanState"),
    liveRegion: document.querySelector("#liveRegion"),
    tabs: [...document.querySelectorAll(".tab")],
    views: [...document.querySelectorAll(".view")],
    switchModuleGrid: document.querySelector("#switchModuleGrid"),
    switchStage: document.querySelector("#switchStage"),
    activityVisual: document.querySelector("#activityVisual"),
    switchTitle: document.querySelector("#switchTitle"),
    switchHint: document.querySelector("#switchHint"),
    hitCount: document.querySelector("#hitCount"),
    averageInterval: document.querySelector("#averageInterval"),
    lastReaction: document.querySelector("#lastReaction"),
    resetSwitch: document.querySelector("#resetSwitch"),
    matchingPrompt: document.querySelector("#matchingPrompt"),
    matchingGrid: document.querySelector("#matchingGrid"),
    nextMatching: document.querySelector("#nextMatching"),
    categoryRow: document.querySelector("#categoryRow"),
    phraseGrid: document.querySelector("#phraseGrid"),
    currentPhrase: document.querySelector("#currentPhrase"),
    repeatPhrase: document.querySelector("#repeatPhrase"),
    letterPrompt: document.querySelector("#letterPrompt"),
    letterGrid: document.querySelector("#letterGrid"),
    nextLetter: document.querySelector("#nextLetter"),
    operationModeGrid: document.querySelector("#operationModeGrid"),
    operationModeTitle: document.querySelector("#operationModeTitle"),
    operationGuide: document.querySelector("#operationGuide"),
    operationStage: document.querySelector("#operationStage"),
    operationPrimary: document.querySelector("#operationPrimary"),
    nextOperationTarget: document.querySelector("#nextOperationTarget"),
    resetOperation: document.querySelector("#resetOperation"),
    operationTrials: document.querySelector("#operationTrials"),
    operationSuccessRate: document.querySelector("#operationSuccessRate"),
    operationAverageDistance: document.querySelector("#operationAverageDistance"),
    participantId: document.querySelector("#participantId"),
    evaluationCondition: document.querySelector("#evaluationCondition"),
    startSession: document.querySelector("#startSession"),
    finishSession: document.querySelector("#finishSession"),
    startTask: document.querySelector("#startTask"),
    openTaskView: document.querySelector("#openTaskView"),
    markTaskSuccess: document.querySelector("#markTaskSuccess"),
    markTaskFail: document.querySelector("#markTaskFail"),
    addMistake: document.querySelector("#addMistake"),
    addBack: document.querySelector("#addBack"),
    addTimingMissed: document.querySelector("#addTimingMissed"),
    addTimingEarly: document.querySelector("#addTimingEarly"),
    addTimingLate: document.querySelector("#addTimingLate"),
    addAssist: document.querySelector("#addAssist"),
    effortRating: document.querySelector("#effortRating"),
    effortRatingValue: document.querySelector("#effortRatingValue"),
    easeRating: document.querySelector("#easeRating"),
    easeRatingValue: document.querySelector("#easeRatingValue"),
    engagementRating: document.querySelector("#engagementRating"),
    engagementRatingValue: document.querySelector("#engagementRatingValue"),
    observerNotes: document.querySelector("#observerNotes"),
    exportEvaluationCsv: document.querySelector("#exportEvaluationCsv"),
    resetEvaluation: document.querySelector("#resetEvaluation"),
    evaluationStatus: document.querySelector("#evaluationStatus"),
    currentTaskTitle: document.querySelector("#currentTaskTitle"),
    currentTaskGuide: document.querySelector("#currentTaskGuide"),
    taskElapsed: document.querySelector("#taskElapsed"),
    taskInputs: document.querySelector("#taskInputs"),
    taskMistakes: document.querySelector("#taskMistakes"),
    taskBacks: document.querySelector("#taskBacks"),
    taskTimingErrors: document.querySelector("#taskTimingErrors"),
    taskAssists: document.querySelector("#taskAssists"),
    evaluationTaskList: document.querySelector("#evaluationTaskList"),
    evaluationResultList: document.querySelector("#evaluationResultList"),
    researchProfileGrid: document.querySelector("#researchProfileGrid"),
    readinessChecklist: document.querySelector("#readinessChecklist"),
    readinessScore: document.querySelector("#readinessScore"),
    researchEnvironment: document.querySelector("#researchEnvironment"),
    deploymentNotes: document.querySelector("#deploymentNotes"),
    copyDeploymentNote: document.querySelector("#copyDeploymentNote"),
    researchProtocolHint: document.querySelector("#researchProtocolHint"),
    totalInputs: document.querySelector("#totalInputs"),
    accuracyRate: document.querySelector("#accuracyRate"),
    mistakeCount: document.querySelector("#mistakeCount"),
    logList: document.querySelector("#logList"),
    exportCsv: document.querySelector("#exportCsv"),
    clearLog: document.querySelector("#clearLog"),
    scanInterval: document.querySelector("#scanInterval"),
    scanIntervalValue: document.querySelector("#scanIntervalValue"),
    autoScan: document.querySelector("#autoScan"),
    speechEnabled: document.querySelector("#speechEnabled"),
    soundEnabled: document.querySelector("#soundEnabled"),
    largeText: document.querySelector("#largeText"),
    highContrast: document.querySelector("#highContrast"),
    toggleScan: document.querySelector("#toggleScan"),
    primarySwitch: document.querySelector("#primarySwitch"),
  };
}
