// =====================================================================
// dom.js — App.svelte が描画したマークアップへの参照を一括取得する
//
// id を変更・追加した場合はここに追記する。各ビューは elements 経由でのみ
// DOM に触れる（直接 querySelector しない）ことで、参照箇所を追いやすくする。
// 例外: 走査エンジン（scan.js）と操作訓練のカーソル更新は動的要素を扱うため
// document.querySelector を併用している。
// =====================================================================

export function collectElements() {
  return {
    scanState: document.querySelector("#scanState"),
    homeSupporterMenu: document.querySelector("#homeSupporterMenu"),
    liveRegion: document.querySelector("#liveRegion"),
    tabs: [...document.querySelectorAll(".tab")],
    views: [...document.querySelectorAll(".view")],
    // 支援者の世界（タブ群）から home へ戻る導線（detailed-design.md §10）。
    homeReturn: document.querySelector("#homeReturn"),
    // P1-1（新4ビュー、detailed-design.md §10）。start/home/game/result。
    startStage: document.querySelector("#startStage"),
    // 利用者の世界の固定文言（表記モードで差し替える）。
    startTitle: document.querySelector("#start-title"),
    startStageLabel: document.querySelector(".start-stage-label"),
    gameTitle: document.querySelector("#game-title"),
    resultTitle: document.querySelector("#result-title"),
    startSettingsLink: document.querySelector("#startSettingsLink"),
    gameTileGrid: document.querySelector("#gameTileGrid"),
    homeEyebrow: document.querySelector("#homeEyebrow"),
    homeTitle: document.querySelector("#home-title"),
    homeGuide: document.querySelector("#homeGuide"),
    gameStage: document.querySelector("#gameStage"),
    gameStageContent: document.querySelector("#gameStageContent"),
    gameProgress: document.querySelector("#gameProgress"),
    gameExit: document.querySelector("#gameExit"),
    resultStats: document.querySelector("#resultStats"),
    resultRetry: document.querySelector("#resultRetry"),
    resultHome: document.querySelector("#resultHome"),
    // P4-3（detailed-design.md §8.2）: キャリブレーションの「候補値を保存
    // しますか」導線。走査対象外・タップ専用（data-scan を付けない、
    // games/gameHost.js が stopPropagation で入力ファネル外にする）。
    calibrationOffer: document.querySelector("#calibrationOffer"),
    calibrationOfferText: document.querySelector("#calibrationOfferText"),
    calibrationSaveOffset: document.querySelector("#calibrationSaveOffset"),
    matchingPrompt: document.querySelector("#matchingPrompt"),
    matchingGrid: document.querySelector("#matchingGrid"),
    nextMatching: document.querySelector("#nextMatching"),
    categoryRow: document.querySelector("#categoryRow"),
    phraseGrid: document.querySelector("#phraseGrid"),
    currentPhrase: document.querySelector("#currentPhrase"),
    repeatPhrase: document.querySelector("#repeatPhrase"),
    letterPrompt: document.querySelector("#letterPrompt"),
    letterGrid: document.querySelector("#letterGrid"),
    nextLetter: document.querySelector("#nextLetter"),
    operationModeGrid: document.querySelector("#operationModeGrid"),
    operationModeTitle: document.querySelector("#operationModeTitle"),
    operationGuide: document.querySelector("#operationGuide"),
    operationStage: document.querySelector("#operationStage"),
    operationPrimary: document.querySelector("#operationPrimary"),
    nextOperationTarget: document.querySelector("#nextOperationTarget"),
    resetOperation: document.querySelector("#resetOperation"),
    operationTrials: document.querySelector("#operationTrials"),
    operationSuccessRate: document.querySelector("#operationSuccessRate"),
    participantId: document.querySelector("#participantId"),
    exportRhythmCsv: document.querySelector("#exportRhythmCsv"),
    exportSlotCsv: document.querySelector("#exportSlotCsv"),
    exportSessionLedgerCsv: document.querySelector("#exportSessionLedgerCsv"),
    exportRawJson: document.querySelector("#exportRawJson"),
    sessionRetentionWarning: document.querySelector("#sessionRetentionWarning"),
    exportScanCsv: document.querySelector("#exportScanCsv"),
    exportRtCsv: document.querySelector("#exportRtCsv"),
    handOverParticipant: document.querySelector("#handOverParticipant"),
    taskMistakes: document.querySelector("#taskMistakes"),
    taskTimingErrors: document.querySelector("#taskTimingErrors"),
    researchProfileGrid: document.querySelector("#researchProfileGrid"),
    offsetDistribution: document.querySelector("#offsetDistribution"),
    readinessChecklist: document.querySelector("#readinessChecklist"),
    readinessScore: document.querySelector("#readinessScore"),
    researchEnvironment: document.querySelector("#researchEnvironment"),
    deploymentNotes: document.querySelector("#deploymentNotes"),
    copyDeploymentNote: document.querySelector("#copyDeploymentNote"),
    researchProtocolHint: document.querySelector("#researchProtocolHint"),
    totalInputs: document.querySelector("#totalInputs"),
    accuracyRate: document.querySelector("#accuracyRate"),
    mistakeCount: document.querySelector("#mistakeCount"),
    logList: document.querySelector("#logList"),
    sessionList: document.querySelector("#sessionList"),
    sessionTrends: document.querySelector("#sessionTrends"),
    trendTabs: document.querySelector("#trendTabs"),
    exportCsv: document.querySelector("#exportCsv"),
    clearLog: document.querySelector("#clearLog"),
    scanInterval: document.querySelector("#scanInterval"),
    scanIntervalValue: document.querySelector("#scanIntervalValue"),
    switchControlMode: document.querySelector("#switchControlMode"),
    switchControlModeNotice: document.querySelector("#switchControlModeNotice"),
    autoScan: document.querySelector("#autoScan"),
    speechEnabled: document.querySelector("#speechEnabled"),
    speechVolume: document.querySelector("#speechVolume"),
    speechVolumeValue: document.querySelector("#speechVolumeValue"),
    soundEnabled: document.querySelector("#soundEnabled"),
    largeText: document.querySelector("#largeText"),
    highContrast: document.querySelector("#highContrast"),
    supporterMessage: document.querySelector("#supporterMessage"),
    rhythmBpm: document.querySelector("#rhythmBpm"),
    rhythmTargetBeats: document.querySelector("#rhythmTargetBeats"),
    visualGuidance: document.querySelector("#visualGuidance"),
    slotCycleMs: document.querySelector("#slotCycleMs"),
    slotCycleMsValue: document.querySelector("#slotCycleMsValue"),
    slotToleranceMs: document.querySelector("#slotToleranceMs"),
    slotToleranceMsValue: document.querySelector("#slotToleranceMsValue"),
    slotL1Rounds: document.querySelector("#slotL1Rounds"),
    slotL1RoundsValue: document.querySelector("#slotL1RoundsValue"),
    slotL2Rounds: document.querySelector("#slotL2Rounds"),
    slotL2RoundsValue: document.querySelector("#slotL2RoundsValue"),
    difficultyMode: document.querySelector("#difficultyMode"),
    textMode: document.querySelector("#textMode"),
    measureModeNotice: document.querySelector("#measureModeNotice"),
    // 設定のタブと、その中身の面。
    settingsTabs: [...document.querySelectorAll(".settings-tab")],
    settingsPanels: [...document.querySelectorAll(".settings-panel")],
    // そくていに入る前の成立確認（src/lib/readinessCheck.js）。
    readinessCheck: document.querySelector("#readinessCheck"),
    readinessLead: document.querySelector("#readinessLead"),
    readinessList: document.querySelector("#readinessList"),
    craneSweepMs: document.querySelector("#craneSweepMs"),
    craneSweepMsValue: document.querySelector("#craneSweepMsValue"),
    craneToleranceR: document.querySelector("#craneToleranceR"),
    craneToleranceRValue: document.querySelector("#craneToleranceRValue"),
    craneTargetTrials: document.querySelector("#craneTargetTrials"),
    craneTargetTrialsValue: document.querySelector("#craneTargetTrialsValue"),
    craneAudioGuidance: document.querySelector("#craneAudioGuidance"),
    hideVisualTasks: document.querySelector("#hideVisualTasks"),
    researcherMode: document.querySelector("#researcherMode"),
    startCalibration: document.querySelector("#startCalibration"),
    toggleScan: document.querySelector("#toggleScan"),
    toggleScanLabel: document.querySelector("#toggleScanLabel"),
    primarySwitch: document.querySelector("#primarySwitch"),
    primarySwitchLabel: document.querySelector("#primarySwitchLabel"),
  };
}
